### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by odb366**
Add item: AI directory with chatbot

### CODE REVIEW

**Comment by Rick-Zo** [comment]
您好，我已收到邮件，查阅后即刻回复^_^

**Comment by ligj1706** [comment]
hanks for the PR! It's not a fit for this project, so I'm closing this.

**Comment by ligj1706** [comment]
thanks for the PR! It's not a fit for this project, so I'm closing this.

**Comment by odb366** [comment]
No probs. Thanks for reviewing it!

**Pull request closed without merging**
